name: Backend CI/CD

on:
  pull_request:
    branches:
      - be/release
    types:
      - closed

env:
  REST_DEPLOY_DIRNAME: rest_deploy
  REST_CLONE_URL: https://github.com/boostcampwm-2022/web17-waglewagle.git
  REST_CLONE_BRANCH: be/release
  REST_SECRET_YML: $REST_DEPLOY_DIRNAME/rest/src/main/resources/secret.yml
  REST_GRADLEW_PATH: $REST_DEPLOY_DIRNAME/rest/gradlew
  TEST3: test3

jobs:
  cicd:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: connect server instance by ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REST_HOST }}
          username: ${{ secrets.REST_USERNAME }}
          password: ${{ secrets.REST_PASSWORD }}
          port: ${{ secrets.REST_PORT }}
          script: |
            echo ${{ env.TEST3 }} > test3

            rm -rf ${{ env.REST_DEPLOY_DIRNAME }}
            git clone -b ${{ env.REST_CLONE_BRANCH }} --single-branch ${{ env.REST_CLONE_URL }} ${{ env.REST_DEPLOY_DIRNAME }}
            echo ${{ secrets.REST_SECRET_YML }} > ${{ env.REST_SECRET_YML }}
            ./${{ env.REST_GRADLEW_PATH }} bootJar

#      코드 가져오기
#      - name: checkout
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.pull_request.base.ref }}

#      빌드
#      - name: java setup
#        uses: actions/setup-java@v3
#        with:
#          java-version: 11
#          distribution: temurin

#      빌드 및 실행
#      - name: build and exec
#        run: |
#          chmod +x gradlew
#          ./gradlew bootJar
#          java -jar ./build/libs/demo*.jar