name: Backend CI/CD

on:
  pull_request:
    branches:
      - be/release
    types:
      - closed

jobs:
  cicd:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

#      빌드
#      - name: java setup
#        uses: actions/setup-java@v3
#        with:
#          java-version: 11
#          distribution: temurin

#      빌드 및 실행
#      - name: build and exec
#        run: |
#          chmod +x gradlew
#          ./gradlew bootJar
#          java -jar ./build/libs/demo*.jar